### ISSUE TITLE
Container has no attribute 'get_widths'

### ISSUE THREAD

**Issue by ingoogni** [wackywendell/tess#6]
>>> c.get_widths()
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    c.get_widths()
  File "[...]\Programs\Python\Python37\lib\site-packages\tess\__init__.py", line 182, in get_widths
    return self._container.get_widths()
AttributeError: 'tess._voro.Container' object has no attribute 'get_widths'

**Comment by wackywendell** [comment]
Hi! Thanks for the report! Could you provide a minimal working example, so I can try and reproduce?

**Comment by ingoogni** [comment]
```
limits=[(6,-2.5,3),(10,9,9)]
vorodata=[
[9.63211,0.1,6.21613],
[6.86854,0.1,5.03901],
[8.64132,0.1,3.8377],
[6.03961,0.1,4.95501],
[7.17098,0.1,8.68142],
[9.63211,3.26588,6.21613],
[6.86854,-0.57493,5.03901],
[8.64132,4.43874,3.8377],
[6.03961,5.5544,4.95501],
[7.17098,6.71017,8.68142],
[9.63211,6.72764,6.21613],
[6.86854,2.83045,5.03901],
[8.64132,8.30812,3.8377],
[6.03961,8.39531,4.95501],
[7.17098,8.66222,8.68142]
]

from tess import Container

c = Container(vorodata, limits=limits, periodic=False)
c.get_widths()

```

**Comment by wackywendell** [comment]
This is addressed with a test in the most recent master, and version 0.3.0 that was uploaded to pypi.

Note that I changed the name to `get_walls`, as that seemed more descriptive - and it should work now!
